/* The following code was generated by JFlex 1.4.3 on 29/10/15 16:20 */

import java.util.regex.PatternSyntaxException;
import java.util.HashMap;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 29/10/15 16:20 from the specification file
 * <tt>LexicalAnalyzer.flex</tt>
 */
class LexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\2\0\1\1\22\0\1\3\7\0\1\6\1\7"+
    "\1\23\1\22\1\0\1\21\1\0\1\24\12\43\1\17\1\16\1\35"+
    "\1\20\1\34\2\0\32\42\6\0\1\33\1\10\1\4\1\15\1\11"+
    "\1\25\1\12\1\27\1\13\2\42\1\30\1\37\1\14\1\5\1\41"+
    "\1\42\1\32\1\31\1\26\2\42\1\36\1\42\1\40\1\42\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\2\3\2\4\1\5\1\6\6\4\1\7"+
    "\1\2\1\10\1\11\1\12\1\13\1\14\4\4\1\15"+
    "\1\16\2\4\1\1\1\4\1\17\1\20\1\4\1\21"+
    "\2\4\1\22\1\4\1\23\1\24\1\25\1\4\1\26"+
    "\1\4\1\27\3\4\1\30\1\31\2\4\1\32\1\0"+
    "\2\4\1\33\1\4\1\34\1\35\3\4\1\36\2\4"+
    "\1\0\1\3\1\4\1\37\1\40\1\41\1\42\2\4"+
    "\1\3\1\43\1\44\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\44\0\154\0\220\0\44\0\44"+
    "\0\264\0\330\0\374\0\u0120\0\u0144\0\u0168\0\44\0\u018c"+
    "\0\44\0\44\0\44\0\44\0\u01b0\0\u01d4\0\u01f8\0\u021c"+
    "\0\u0240\0\u0264\0\u0288\0\u02ac\0\u02d0\0\u02f4\0\u0318\0\374"+
    "\0\374\0\u033c\0\374\0\u0360\0\u0384\0\374\0\u03a8\0\374"+
    "\0\44\0\44\0\u03cc\0\374\0\u03f0\0\374\0\u0414\0\u0438"+
    "\0\u045c\0\44\0\44\0\u0480\0\u04a4\0\u04c8\0\u04ec\0\u0510"+
    "\0\u0534\0\374\0\u0558\0\374\0\374\0\u057c\0\u05a0\0\u05c4"+
    "\0\374\0\u05e8\0\u060c\0\u0630\0\u0318\0\u0654\0\374\0\374"+
    "\0\374\0\374\0\u0678\0\u069c\0\u04ec\0\374\0\374\0\374";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\3\13\1\30"+
    "\1\31\1\32\1\33\1\34\2\13\1\35\1\13\1\36"+
    "\46\0\1\4\45\0\1\13\1\37\2\0\6\13\7\0"+
    "\7\13\2\0\6\13\4\0\2\13\2\0\5\13\1\40"+
    "\7\0\5\13\1\41\1\13\2\0\6\13\4\0\2\13"+
    "\2\0\1\13\1\42\4\13\7\0\7\13\2\0\2\13"+
    "\1\43\3\13\4\0\2\13\2\0\4\13\1\44\1\13"+
    "\7\0\3\13\1\45\3\13\2\0\6\13\4\0\2\13"+
    "\2\0\6\13\7\0\7\13\2\0\6\13\4\0\2\13"+
    "\2\0\6\13\7\0\1\46\6\13\2\0\6\13\4\0"+
    "\1\13\1\47\2\0\6\13\7\0\7\13\2\0\6\13"+
    "\4\0\1\13\1\50\2\0\6\13\7\0\7\13\2\0"+
    "\6\13\20\0\1\51\43\0\1\52\27\0\1\13\1\53"+
    "\2\0\3\13\1\54\2\13\7\0\5\13\1\55\1\13"+
    "\2\0\6\13\4\0\1\13\1\56\2\0\6\13\7\0"+
    "\2\13\1\57\4\13\2\0\6\13\4\0\2\13\2\0"+
    "\1\13\1\60\4\13\7\0\7\13\2\0\6\13\4\0"+
    "\2\13\2\0\4\13\1\61\1\13\7\0\7\13\2\0"+
    "\6\13\20\0\1\62\43\0\1\63\27\0\2\13\2\0"+
    "\6\13\7\0\2\13\1\64\4\13\2\0\6\13\4\0"+
    "\2\13\2\0\6\13\7\0\5\13\1\65\1\13\2\0"+
    "\6\13\4\0\2\66\2\0\6\66\7\0\7\66\2\0"+
    "\5\66\1\36\2\67\1\0\1\67\1\70\1\37\2\67"+
    "\6\37\7\67\7\37\2\67\6\37\4\0\2\13\2\0"+
    "\2\13\1\71\3\13\7\0\7\13\2\0\6\13\4\0"+
    "\2\13\2\0\5\13\1\72\7\0\7\13\2\0\6\13"+
    "\4\0\2\13\2\0\6\13\7\0\4\13\1\73\2\13"+
    "\2\0\6\13\4\0\2\13\2\0\6\13\7\0\1\13"+
    "\1\74\5\13\2\0\6\13\4\0\2\13\2\0\6\13"+
    "\7\0\5\13\1\75\1\13\2\0\6\13\4\0\1\13"+
    "\1\76\2\0\6\13\7\0\7\13\2\0\6\13\4\0"+
    "\2\13\2\0\1\13\1\77\4\13\7\0\7\13\2\0"+
    "\6\13\4\0\2\13\2\0\6\13\7\0\6\13\1\100"+
    "\2\0\6\13\4\0\2\13\2\0\5\13\1\101\7\0"+
    "\7\13\2\0\6\13\4\0\2\13\2\0\3\13\1\102"+
    "\2\13\7\0\7\13\2\0\6\13\4\0\2\13\2\0"+
    "\3\13\1\103\2\13\7\0\7\13\2\0\6\13\4\0"+
    "\2\66\2\0\6\66\7\0\7\66\2\0\6\66\2\67"+
    "\1\0\1\67\1\104\41\67\1\0\1\67\1\70\1\105"+
    "\2\67\6\37\7\67\7\37\2\67\6\37\4\0\2\13"+
    "\2\0\3\13\1\106\2\13\7\0\7\13\2\0\6\13"+
    "\4\0\2\13\2\0\1\13\1\107\4\13\7\0\7\13"+
    "\2\0\6\13\4\0\2\13\2\0\6\13\7\0\7\13"+
    "\2\0\1\13\1\110\4\13\4\0\2\13\2\0\4\13"+
    "\1\111\1\13\7\0\7\13\2\0\6\13\4\0\2\13"+
    "\2\0\5\13\1\112\7\0\7\13\2\0\6\13\4\0"+
    "\2\13\2\0\6\13\7\0\3\13\1\113\3\13\2\0"+
    "\6\13\4\0\2\13\2\0\4\13\1\114\1\13\7\0"+
    "\7\13\2\0\6\13\2\67\1\0\1\67\1\104\1\115"+
    "\36\67\4\0\2\13\2\0\4\13\1\116\1\13\7\0"+
    "\7\13\2\0\6\13\4\0\2\13\2\0\1\13\1\117"+
    "\4\13\7\0\7\13\2\0\6\13\4\0\2\13\2\0"+
    "\6\13\7\0\1\13\1\120\5\13\2\0\6\13";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1728];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\1\1\1\11\2\1\2\11\6\1\1\11"+
    "\1\1\4\11\24\1\2\11\7\1\2\11\3\1\1\0"+
    "\14\1\1\0\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private static HashMap<Object, Integer> varNameMap = new HashMap<Object, Integer>();
    public static HashMap<Object, Integer> getVarNameMap() {
        return varNameMap;
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexicalAnalyzer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 100) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, PatternSyntaxException, SyntaxErrorException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { return new Symbol(LexicalUnit.DO, yyline, yycolumn, yytext());
          }
        case 38: break;
        case 22: 
          { return new Symbol(LexicalUnit.FI, yyline, yycolumn, yytext());
          }
        case 39: break;
        case 18: 
          { return new Symbol(LexicalUnit.IF, yyline, yycolumn, yytext());
          }
        case 40: break;
        case 34: 
          { return new Symbol(LexicalUnit.READ, yyline, yycolumn, yytext());
          }
        case 41: break;
        case 29: 
          { return new Symbol(LexicalUnit.FOR, yyline, yycolumn, yytext());
          }
        case 42: break;
        case 31: 
          { return new Symbol(LexicalUnit.ELSE, yyline, yycolumn, yytext());
          }
        case 43: break;
        case 14: 
          { return new Symbol(LexicalUnit.SMALLER, yyline, yycolumn, yytext());
          }
        case 44: break;
        case 27: 
          { return new Symbol(LexicalUnit.END, yyline, yycolumn, yytext());
          }
        case 45: break;
        case 7: 
          { return new Symbol(LexicalUnit.SEMICOLON, yyline, yycolumn, yytext());
          }
        case 46: break;
        case 10: 
          { return new Symbol(LexicalUnit.PLUS, yyline, yycolumn, yytext());
          }
        case 47: break;
        case 9: 
          { return new Symbol(LexicalUnit.MINUS, yyline, yycolumn, yytext());
          }
        case 48: break;
        case 12: 
          { return new Symbol(LexicalUnit.DIVIDE, yyline, yycolumn, yytext());
          }
        case 49: break;
        case 26: 
          { throw new SyntaxErrorException(yytext()+"\n Error: Variable names must start with a letter.");
          }
        case 50: break;
        case 28: 
          { return new Symbol(LexicalUnit.NOT, yyline, yycolumn, yytext());
          }
        case 51: break;
        case 23: 
          { return new Symbol(LexicalUnit.TO, yyline, yycolumn, yytext());
          }
        case 52: break;
        case 17: 
          { return new Symbol(LexicalUnit.BY, yyline, yycolumn, yytext());
          }
        case 53: break;
        case 4: 
          { Symbol varName = new Symbol(LexicalUnit.VARNAME, yyline, yycolumn, yytext()); 
            if(!varNameMap.containsKey(varName.getValue())) {
                varNameMap.put(varName.getValue(), varName.getLine());
            }
            return varName;
          }
        case 54: break;
        case 32: 
          { return new Symbol(LexicalUnit.FROM, yyline, yycolumn, yytext());
          }
        case 55: break;
        case 20: 
          { return new Symbol(LexicalUnit.ASSIGN, yyline, yycolumn, yytext());
          }
        case 56: break;
        case 36: 
          { return new Symbol(LexicalUnit.WHILE, yyline, yycolumn, yytext());
          }
        case 57: break;
        case 2: 
          { throw new SyntaxErrorException(yytext());
          }
        case 58: break;
        case 5: 
          { return new Symbol(LexicalUnit.LEFT_PARENTHESIS, yyline, yycolumn, yytext());
          }
        case 59: break;
        case 13: 
          { return new Symbol(LexicalUnit.GREATER, yyline, yycolumn, yytext());
          }
        case 60: break;
        case 25: 
          { return new Symbol(LexicalUnit.SMALLER_EQUAL, yyline, yycolumn, yytext());
          }
        case 61: break;
        case 33: 
          { return new Symbol(LexicalUnit.THEN, yyline, yycolumn, yytext());
          }
        case 62: break;
        case 15: 
          { return new Symbol(LexicalUnit.OD, yyline, yycolumn, yytext());
          }
        case 63: break;
        case 11: 
          { return new Symbol(LexicalUnit.TIMES, yyline, yycolumn, yytext());
          }
        case 64: break;
        case 30: 
          { return new Symbol(LexicalUnit.AND, yyline, yycolumn, yytext());
          }
        case 65: break;
        case 6: 
          { return new Symbol(LexicalUnit.RIGHT_PARENTHESIS, yyline, yycolumn, yytext());
          }
        case 66: break;
        case 1: 
          { return new Symbol(LexicalUnit.NUMBER, yyline, yycolumn, yytext());
          }
        case 67: break;
        case 37: 
          { return new Symbol(LexicalUnit.PRINT, yyline, yycolumn, yytext());
          }
        case 68: break;
        case 24: 
          { return new Symbol(LexicalUnit.GREATER_EQUAL, yyline, yycolumn, yytext());
          }
        case 69: break;
        case 16: 
          { return new Symbol(LexicalUnit.OR, yyline, yycolumn, yytext());
          }
        case 70: break;
        case 21: 
          { return new Symbol(LexicalUnit.DIFFERENT, yyline, yycolumn, yytext());
          }
        case 71: break;
        case 8: 
          { return new Symbol(LexicalUnit.EQUAL, yyline, yycolumn, yytext());
          }
        case 72: break;
        case 35: 
          { return new Symbol(LexicalUnit.BEG, yyline, yycolumn, yytext());
          }
        case 73: break;
        case 3: 
          { 
          }
        case 74: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 	return new Symbol(LexicalUnit.END_OF_STREAM,yyline, yycolumn);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
